require 'pry'
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

RSpec.describe "Fibonacci even number Summer" do
  it 'sums even fibonacci even numbers up to 89' do
    expect(fib_summer(89)).to eq(44)
  end

  it 'sums even fibonacci even numbers up to 4,000,000,000' do
    expect(fib_summer(4000000)).to eq(4613732)
  end
end

def fib_summer max
  num_1 = 1
  num_2 = 1
  all_fibs =[1]
  even_fibs = []

  loop do 
    sum = num_1 + num_2
    all_fibs << sum
    even_fibs << sum if sum.even?

    if sum + num_2 >= max
      return even_fibs.inject(:+)
    end

    num_1 = num_2
    num_2 = sum
  end
end